# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oppo/R11/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/oppo/R11

PRODUCT_COPY_FILES += \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16051/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16051/Bluetooth_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16051/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16051/General_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16051/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16051/Global_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16051/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16051/Handset_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16051/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16051/Hdmi_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16051/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16051/Headset_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16051/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16051/Speaker_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16051/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16051/adsp_avs_config.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16103/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16103/Bluetooth_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16103/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16103/General_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16103/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16103/Global_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16103/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16103/Handset_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16103/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16103/Hdmi_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16103/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16103/Headset_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16103/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16103/Speaker_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16118/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16118/Bluetooth_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16118/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16118/General_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16118/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16118/Global_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16118/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16118/Handset_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16118/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16118/Hdmi_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16118/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16118/Headset_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16118/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16118/Speaker_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/qdcm_calib_data_oppo16051samsung_s6e3fa3_1080p_cmd_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_oppo16051samsung_s6e3fa3_1080p_cmd_mode_dsi_panel.xml \
    vendor/oppo/R11/proprietary/vendor/etc/qdcm_calib_data_oppo16103jdi_r63452_1080p_cmd_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_oppo16103jdi_r63452_1080p_cmd_mode_dsi_panel.xml \
    vendor/oppo/R11/proprietary/vendor/etc/qdcm_calib_data_oppo16118samsung_s6e3fa3_1080p_cmd_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_oppo16118samsung_s6e3fa3_1080p_cmd_mode_dsi_panel.xml \
    vendor/oppo/R11/proprietary/vendor/firmware/a512_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b00 \
    vendor/oppo/R11/proprietary/vendor/firmware/a512_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b01 \
    vendor/oppo/R11/proprietary/vendor/firmware/a512_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b02 \
    vendor/oppo/R11/proprietary/vendor/firmware/a512_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.elf \
    vendor/oppo/R11/proprietary/vendor/firmware/a512_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.mdt \
    vendor/oppo/R11/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/oppo/R11/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/oppo/R11/proprietary/vendor/firmware/a540_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_gpmu.fw2 \
    vendor/oppo/R11/proprietary/vendor/firmware/tp/16051/16051_FW_S3508_SYNAPTICS.img:$(TARGET_COPY_OUT_VENDOR)/firmware/tp/16051/16051_FW_S3508_SYNAPTICS.img \
    vendor/oppo/R11/proprietary/vendor/firmware/tp/16051/16051_Limit_data.img:$(TARGET_COPY_OUT_VENDOR)/firmware/tp/16051/16051_Limit_data.img \
    vendor/oppo/R11/proprietary/vendor/firmware/tp/16103/16103_FW_S3320_JDI.img:$(TARGET_COPY_OUT_VENDOR)/firmware/tp/16103/16103_FW_S3320_JDI.img \
    vendor/oppo/R11/proprietary/vendor/firmware/tp/16103/16103_Limit_data.img:$(TARGET_COPY_OUT_VENDOR)/firmware/tp/16103/16103_Limit_data.img \
    vendor/oppo/R11/proprietary/vendor/firmware/tp/16118/16118_FW_S3508_SYNAPTICS.img:$(TARGET_COPY_OUT_VENDOR)/firmware/tp/16118/16118_FW_S3508_SYNAPTICS.img \
    vendor/oppo/R11/proprietary/vendor/firmware/tp/16118/16118_Limit_data.img:$(TARGET_COPY_OUT_VENDOR)/firmware/tp/16118/16118_Limit_data.img \
    vendor/oppo/R11/proprietary/vendor/lib/hw/camera.sdm660.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.sdm660.so \
    vendor/oppo/R11/proprietary/vendor/lib/hw/gatekeeper.sdm660.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gatekeeper.sdm660.so \
    vendor/oppo/R11/proprietary/vendor/lib/hw/keystore.sdm660.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/keystore.sdm660.so \
    vendor/oppo/R11/proprietary/vendor/lib/libPolarrRender.so:$(TARGET_COPY_OUT_VENDOR)/lib/libPolarrRender.so \
    vendor/oppo/R11/proprietary/vendor/lib/libSensorManagerHAL.so:$(TARGET_COPY_OUT_VENDOR)/lib/libSensorManagerHAL.so \
    vendor/oppo/R11/proprietary/vendor/lib/libStDualCam.so:$(TARGET_COPY_OUT_VENDOR)/lib/libStDualCam.so \
    vendor/oppo/R11/proprietary/vendor/lib/libVDUpScale.so:$(TARGET_COPY_OUT_VENDOR)/lib/libVDUpScale.so \
    vendor/oppo/R11/proprietary/vendor/lib/libcamera_core_hwi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcamera_core_hwi.so \
    vendor/oppo/R11/proprietary/vendor/lib/libfilter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfilter.so \
    vendor/oppo/R11/proprietary/vendor/lib/libmmcamera2_mct_shimlayer.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_mct_shimlayer.so \
    vendor/oppo/R11/proprietary/vendor/lib/libmmcamera_interface.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_interface.so \
    vendor/oppo/R11/proprietary/vendor/lib/libmmjpeg_interface.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmjpeg_interface.so \
    vendor/oppo/R11/proprietary/vendor/lib/libmmlib2d_interface.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmlib2d_interface.so \
    vendor/oppo/R11/proprietary/vendor/lib/libmms_gyro_vstab.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmms_gyro_vstab.so \
    vendor/oppo/R11/proprietary/vendor/lib/libmms_gyro_vstab_auth.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmms_gyro_vstab_auth.so \
    vendor/oppo/R11/proprietary/vendor/lib/libmms_hal_vstab.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmms_hal_vstab.so \
    vendor/oppo/R11/proprietary/vendor/lib/libmms_warper_vstab.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmms_warper_vstab.so \
    vendor/oppo/R11/proprietary/vendor/lib/libmpbase.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmpbase.so \
    vendor/oppo/R11/proprietary/vendor/lib/libocam_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libocam_common.so \
    vendor/oppo/R11/proprietary/vendor/lib/liboppo_platform_hwi.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboppo_platform_hwi.so \
    vendor/oppo/R11/proprietary/vendor/lib/liboppoalgolib.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboppoalgolib.so \
    vendor/oppo/R11/proprietary/vendor/lib/liboppocamalgo_daemon.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboppocamalgo_daemon.so \
    vendor/oppo/R11/proprietary/vendor/lib/libopposfr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libopposfr.so \
    vendor/oppo/R11/proprietary/vendor/lib/libqomx_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_core.so \
    vendor/oppo/R11/proprietary/vendor/lib/libstface_fd_api.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstface_fd_api.so \
    vendor/oppo/R11/proprietary/vendor/lib64/hw/gatekeeper.sdm660.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gatekeeper.sdm660.so \
    vendor/oppo/R11/proprietary/vendor/lib64/hw/keystore.sdm660.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/keystore.sdm660.so
