# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oppo/R11/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/oppo/R11

PRODUCT_COPY_FILES += \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16051/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16051/Bluetooth_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16051/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16051/General_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16051/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16051/Global_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16051/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16051/Handset_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16051/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16051/Hdmi_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16051/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16051/Headset_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16051/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16051/Speaker_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16051/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16051/adsp_avs_config.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16103/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16103/Bluetooth_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16103/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16103/General_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16103/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16103/Global_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16103/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16103/Handset_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16103/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16103/Hdmi_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16103/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16103/Headset_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16103/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16103/Speaker_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16118/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16118/Bluetooth_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16118/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16118/General_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16118/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16118/Global_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16118/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16118/Handset_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16118/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16118/Hdmi_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16118/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16118/Headset_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/acdbdata/16118/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/16118/Speaker_cal.acdb \
    vendor/oppo/R11/proprietary/vendor/etc/qdcm_calib_data_oppo16051samsung_s6e3fa3_1080p_cmd_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_oppo16051samsung_s6e3fa3_1080p_cmd_mode_dsi_panel.xml \
    vendor/oppo/R11/proprietary/vendor/etc/qdcm_calib_data_oppo16103jdi_r63452_1080p_cmd_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_oppo16103jdi_r63452_1080p_cmd_mode_dsi_panel.xml \
    vendor/oppo/R11/proprietary/vendor/etc/qdcm_calib_data_oppo16118samsung_s6e3fa3_1080p_cmd_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_oppo16118samsung_s6e3fa3_1080p_cmd_mode_dsi_panel.xml \
    vendor/oppo/R11/proprietary/vendor/firmware/tp/16051/16051_FW_S3508_SYNAPTICS.img:$(TARGET_COPY_OUT_VENDOR)/firmware/tp/16051/16051_FW_S3508_SYNAPTICS.img \
    vendor/oppo/R11/proprietary/vendor/firmware/tp/16051/16051_Limit_data.img:$(TARGET_COPY_OUT_VENDOR)/firmware/tp/16051/16051_Limit_data.img \
    vendor/oppo/R11/proprietary/vendor/firmware/tp/16103/16103_FW_S3320_JDI.img:$(TARGET_COPY_OUT_VENDOR)/firmware/tp/16103/16103_FW_S3320_JDI.img \
    vendor/oppo/R11/proprietary/vendor/firmware/tp/16103/16103_Limit_data.img:$(TARGET_COPY_OUT_VENDOR)/firmware/tp/16103/16103_Limit_data.img \
    vendor/oppo/R11/proprietary/vendor/firmware/tp/16118/16118_FW_S3508_SYNAPTICS.img:$(TARGET_COPY_OUT_VENDOR)/firmware/tp/16118/16118_FW_S3508_SYNAPTICS.img \
    vendor/oppo/R11/proprietary/vendor/firmware/tp/16118/16118_Limit_data.img:$(TARGET_COPY_OUT_VENDOR)/firmware/tp/16118/16118_Limit_data.img \
    vendor/oppo/R11/proprietary/vendor/lib/hw/gatekeeper.sdm660.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gatekeeper.sdm660.so \
    vendor/oppo/R11/proprietary/vendor/lib/hw/keystore.sdm660.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/keystore.sdm660.so \
    vendor/oppo/R11/proprietary/vendor/lib64/hw/gatekeeper.sdm660.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gatekeeper.sdm660.so \
    vendor/oppo/R11/proprietary/vendor/lib64/hw/keystore.sdm660.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/keystore.sdm660.so
